apiVersion: eventstreams.ibm.com/v1beta2
kind: KafkaUser
metadata:
  labels:
    app.kubernetes.io/instance: es
    eventstreams.ibm.com/cluster: es
  name: quotas-user
  namespace: eventstreams
spec:
  quotas:
    producerByteRate: 250000
  authentication:
    type: scram-sha-512
  authorization:
    acls:
      - host: '*'
        operations:
          - Write
          - Read
        resource:
          name: '*'
          patternType: literal
          type: topic
      - host: '*'
        operations:
          - Read
        resource:
          name: '*'
          patternType: literal
          type: group
    type: simple
